title = "ViV state maps"
output_dir = "docs"

[[states]]
number = 393
description = "The original ViV: Viking Violence."

[[states.alliances]]
name = "ViV"
color = "#00f"

[[states.alliances]]
name = "viv"
color = "#909"

[[states]]
number = 999
description = "For me to test new things."
csv = "state-test.csv"
file_base = "test"
